# Deep learning

- understand LSTM and RNN
- use LSTM to generate text from source corpus
- create qa chatbots with python

### Artificial Neuron
- input will be value of feature
- inputs are multiplied by weight (random num)
- activation function
- bias term (remove the problem of weight being zero) 

# $$\sum_{i=0->n}wixi + b$$ 

- once we have many perceptrons in a network we'll see how we can easily extend this to a matrix form

- rather than using just treshold, we can use sigmoid.. gives better meaning
- tanh is also good func, but output can be -1 to 1 -> [e^x+e^(-x)]/[e^x - e^(-x)]
- Relu -> if greater than  zero, return what's input, else return 0

# Keras

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
type(iris)

sklearn.utils.Bunch

In [6]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [9]:
X = iris.data

In [10]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y= iris.target

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [13]:
 # doing one hot encoding

In [14]:
# class 0 ---> [1 0 0]
# class 1 ---> [0 1 0]
# class 2 ---> [0 0 1]

In [23]:
from tensorflow.keras.utils import to_categorical

In [26]:
y = to_categorical(y)

In [27]:
y.shape

(150, 3)

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state =42)

In [30]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [32]:
from sklearn.preprocessing import MinMaxScaler

In [35]:
scaler_object = MinMaxScaler()

In [36]:
scaler_object.fit(X_train)

MinMaxScaler()

In [37]:
scaled_X_train = scaler_object.transform(X_train)

In [38]:
scaled_X_test = scaler_object.transform(X_test)

In [39]:
# scaled_X_train

In [40]:
from tensorflow.keras.models import Sequential

In [41]:
from keras.layers import Dense

In [42]:
model = Sequential()

In [44]:
model.add(Dense(8, input_dim=4, activation= 'relu'))
model.add(Dense(8, input_dim=4, activation= 'relu'))
model.add(Dense(3, activation='softmax')) # each have a prob of which it belongs
model.compile(loss = 'categorical_crossentropy', optimizer= 'adam', metrics = ['accuracy'])

In [45]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [46]:
model.fit(scaled_X_train, y_train, epochs=150, verbose=2)

Epoch 1/150
4/4 - 1s - loss: 1.0717 - accuracy: 0.6500 - 531ms/epoch - 133ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0609 - accuracy: 0.6600 - 11ms/epoch - 3ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0524 - accuracy: 0.6200 - 11ms/epoch - 3ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0433 - accuracy: 0.6100 - 12ms/epoch - 3ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0361 - accuracy: 0.6300 - 11ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0281 - accuracy: 0.7200 - 9ms/epoch - 2ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0205 - accuracy: 0.6700 - 9ms/epoch - 2ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0132 - accuracy: 0.6600 - 11ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0064 - accuracy: 0.6700 - 11ms/epoch - 3ms/step
Epoch 10/150
4/4 - 0s - loss: 0.9999 - accuracy: 0.6700 - 11ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 0.9929 - accuracy: 0.6600 - 9ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 0.9860 - accuracy: 0.6500 - 11ms/epoch - 3ms/step
Epoch 13/150
4/4 - 0s - loss: 0.9795 - accuracy: 

Epoch 104/150
4/4 - 0s - loss: 0.4511 - accuracy: 0.9300 - 9ms/epoch - 2ms/step
Epoch 105/150
4/4 - 0s - loss: 0.4483 - accuracy: 0.9300 - 10ms/epoch - 2ms/step
Epoch 106/150
4/4 - 0s - loss: 0.4452 - accuracy: 0.9300 - 11ms/epoch - 3ms/step
Epoch 107/150
4/4 - 0s - loss: 0.4426 - accuracy: 0.8900 - 9ms/epoch - 2ms/step
Epoch 108/150
4/4 - 0s - loss: 0.4408 - accuracy: 0.8600 - 9ms/epoch - 2ms/step
Epoch 109/150
4/4 - 0s - loss: 0.4383 - accuracy: 0.8600 - 8ms/epoch - 2ms/step
Epoch 110/150
4/4 - 0s - loss: 0.4353 - accuracy: 0.8600 - 10ms/epoch - 2ms/step
Epoch 111/150
4/4 - 0s - loss: 0.4336 - accuracy: 0.8400 - 11ms/epoch - 3ms/step
Epoch 112/150
4/4 - 0s - loss: 0.4310 - accuracy: 0.8400 - 10ms/epoch - 2ms/step
Epoch 113/150
4/4 - 0s - loss: 0.4279 - accuracy: 0.8600 - 8ms/epoch - 2ms/step
Epoch 114/150
4/4 - 0s - loss: 0.4251 - accuracy: 0.8900 - 10ms/epoch - 2ms/step
Epoch 115/150
4/4 - 0s - loss: 0.4219 - accuracy: 0.9000 - 11ms/epoch - 3ms/step
Epoch 116/150
4/4 - 0s - loss: 0.

In [64]:
scaled_X_test

array([[ 0.52941176,  0.36363636,  0.64285714,  0.45833333],
       [ 0.41176471,  0.81818182,  0.10714286,  0.08333333],
       [ 1.        ,  0.27272727,  1.03571429,  0.91666667],
       [ 0.5       ,  0.40909091,  0.60714286,  0.58333333],
       [ 0.73529412,  0.36363636,  0.66071429,  0.54166667],
       [ 0.32352941,  0.63636364,  0.07142857,  0.125     ],
       [ 0.38235294,  0.40909091,  0.44642857,  0.5       ],
       [ 0.76470588,  0.5       ,  0.71428571,  0.91666667],
       [ 0.55882353,  0.09090909,  0.60714286,  0.58333333],
       [ 0.44117647,  0.31818182,  0.5       ,  0.45833333],
       [ 0.64705882,  0.54545455,  0.71428571,  0.79166667],
       [ 0.14705882,  0.45454545,  0.05357143,  0.        ],
       [ 0.35294118,  0.68181818,  0.03571429,  0.04166667],
       [ 0.17647059,  0.5       ,  0.07142857,  0.        ],
       [ 0.23529412,  0.81818182,  0.07142857,  0.08333333],
       [ 0.58823529,  0.59090909,  0.64285714,  0.625     ],
       [ 0.64705882,  0.

In [74]:
predicted = model.predict(scaled_X_test)

2/2 [==============================] - 0s 3ms/step


In [75]:
classes_x=np.argmax(predicted,axis=1)

In [76]:
classes_x

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 2, 2, 1, 2], dtype=int64)

In [77]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0

In [78]:
# now we need to see how well we performed

In [79]:
y_test_mod = y_test.argmax(axis =1)

In [80]:
from sklearn.metrics import confusion_matrix, classification_report

In [81]:
confusion_matrix(y_test_mod, classes_x)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  0, 16]], dtype=int64)

In [82]:
print(classification_report(y_test.argmax(axis=1), classes_x))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.93      0.97        15
           2       0.94      1.00      0.97        16

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [83]:
model.save('myfirstmodel.h5')

In [84]:
# load our model

In [85]:
from tensorflow.keras.models import load_model

In [86]:
new_model = load_model('myfirstmodel.h5')

# Recurrent Neural Network


- modelled to work with sequence data
 - time series
 - sentences
 - audio
 - car trajectories
 - music

## Recrrunt neuron
- sends output back to itself
- if we unroll it over time , the t-1 output is t input, and t output is t+1 input with input at that step


- it gives a peception of the neurons having some form of memory   
- sequence to sequence (sales)
- sequence to vector   (movie review)
- vector to sequence   (hello -> hellow, how are you)
-

## LSTM , GRU and TextGeneration

In [87]:
# issue with RNN is forgetting old trained
# LSTM(long short term memory) solve this
# h(t) used to denote the output of each neuron
# Keras have a api that makes lstm and rnn to work easily
# 

## TextGeneration
part 1

In [88]:
def read_file(filepath):
    with open(filepath) as f:
        str_text = f.read()
    return str_text

In [90]:
# tokenization and cleaning
# we can use spcy

In [91]:
import spacy

In [102]:
nlp = spacy.load('en_core_web_lg', disable= ['parser', 'tagger', 'ner'])

In [103]:
nlp.max_length = 1198623

In [104]:
def separate_punc(doc_text):
    return [token.text.lower() for token in nlp(doc_text) if token.text not in '\n\n \n\n\n!"-#$%&()--.*+,-/:;<=>?@[\\]^_`{|}~\t\n ']

In [105]:
d = read_file('resources/moby_dick_four_chapters.txt')

In [106]:
tokens = separate_punc(d)

In [107]:
len(tokens)

11338

In [109]:
# we are gonna pass 25 words and let our neural network predict the 26th word

In [110]:
train_len = 25 + 1
text_sequences = []
for i in range(train_len, len(tokens)):
    seq = tokens[i-train_len:i]
    
    text_sequences.append(seq)

In [111]:
type(text_sequences)

list

In [117]:
' '.join(text_sequences[0])

'call me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on'

In [116]:
' '.join(text_sequences[1])

'me ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore'

In [118]:
' '.join(text_sequences[2])

'ishmael some years ago never mind how long precisely having little or no money in my purse and nothing particular to interest me on shore i'

In [119]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [120]:
tokenizer = Tokenizer()

In [121]:
tokenizer.fit_on_texts(text_sequences)

In [122]:
sequences = tokenizer.texts_to_sequences(text_sequences)

In [123]:
# sequences[1]

In [124]:
for i in sequences[0]:
    print(f'{i} : {tokenizer.index_word[i]}')

956 : call
14 : me
263 : ishmael
51 : some
261 : years
408 : ago
87 : never
219 : mind
129 : how
111 : long
954 : precisely
260 : having
50 : little
43 : or
38 : no
314 : money
7 : in
23 : my
546 : purse
3 : and
150 : nothing
259 : particular
6 : to
2713 : interest
14 : me
24 : on


In [125]:
 import numpy as np

In [126]:
sequences = np.array(sequences)

In [127]:
sequences

array([[ 956,   14,  263, ..., 2713,   14,   24],
       [  14,  263,   51, ...,   14,   24,  957],
       [ 263,   51,  261, ...,   24,  957,    5],
       ...,
       [ 952,   12,  166, ...,  262,   53,    2],
       [  12,  166, 2712, ...,   53,    2, 2718],
       [ 166, 2712,    3, ...,    2, 2718,   26]])

In [136]:
vocabulary_size = len(tokenizer.word_counts)
vocabulary_size

2718

## Text Generation with Python and Keras

- create the LSTM based Model
- split the data into features and labels
 - x features (first n words of sequence)
 - y label (next word after sequence)
- fit the model

In [128]:
# split the data 

In [129]:
from tensorflow.keras.utils import to_categorical

In [132]:
X = sequences[:, :-1]

In [133]:
y= sequences[:, -1]

In [137]:
y = to_categorical(y, num_classes= vocabulary_size+1)

In [144]:
seq_len = X.shape[1]
seq_len

25

In [139]:
X.shape

(11312, 25)

In [141]:
y.shape

(11312, 2719)

In [143]:
# LSTM layer for sequences and embedding layer to deal with vocabulary

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding

In [145]:
# Turns positive integers (indexes) into dense vectors of fixed size

def create_model(vocabulary_size, seq_len):
    model = Sequential()
    model.add(Embedding(vocabulary_size, seq_len, input_length= seq_len))
    model.add(LSTM(50, return_sequences= True))
    model.add(LSTM(50))
    model.add(Dense(50, activation='relu'))
    
    model.add(Dense(vocabulary_size, activation= 'softmax'))
    
    model.compile(loss ='categorical_crossentropy', optimizer= 'adam', metrics=['accuracy'])
    model.summary()
    return model

In [146]:
model = create_model(vocabulary_size+1, seq_len)

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 25)            67975     
                                                                 
 lstm (LSTM)                 (None, 25, 50)            15200     
                                                                 
 lstm_1 (LSTM)               (None, 50)                20200     
                                                                 
 dense_3 (Dense)             (None, 50)                2550      
                                                                 
 dense_4 (Dense)             (None, 2719)              138669    
                                                                 
Total params: 244,594
Trainable params: 244,594
Non-trainable params: 0
_________________________________________________________________


In [147]:
from pickle import dump, load

In [148]:
model.fit(X, y, batch_size = 128, epochs=2, verbose=1)

Epoch 1/2
89/89 [==============================] - 15s 62ms/step - loss: 6.9740 - accuracy: 0.0493
Epoch 2/2
89/89 [==============================] - 6s 64ms/step - loss: 6.3744 - accuracy: 0.0529


In [149]:
model.save('my_mobydick_model.h5')

In [150]:
dump(tokenizer, open('my_simpletokenizer', 'wb'))

In [151]:
## Generate new text

In [153]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [205]:
def generate_text(model, tokenizer, seq_len, seed_text, num_gen_words):
    output_text = []
    input_text = seed_text
    
    for i in range(num_gen_words):
        encoded_text = tokenizer.texts_to_sequences([input_text])[0]
        pad_encoded = pad_sequences([encoded_text], maxlen = seq_len, truncating='pre')
        
        
        predict_x=model.predict(pad_encoded)[0]
        pred_word_ind=np.argmax(predict_x)
        
        
        pred_word = tokenizer.index_word[pred_word_ind]
        
        input_text += ' '+ pred_word
        output_text.append(pred_word)
    return ' '.join(output_text)

In [206]:
text_sequences[0]

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on']

In [207]:
import random 
random.seed(101)
random_pick = random.randint(0, len(text_sequences))

In [208]:
random_seed_text = text_sequences[random_pick]

In [209]:
random_seed_text

['thought',
 'i',
 'to',
 'myself',
 'the',
 'man',
 "'s",
 'a',
 'human',
 'being',
 'just',
 'as',
 'i',
 'am',
 'he',
 'has',
 'just',
 'as',
 'much',
 'reason',
 'to',
 'fear',
 'me',
 'as',
 'i',
 'have']

In [210]:
seed_txt = ' '.join(random_seed_text)

In [211]:
seed_txt

"thought i to myself the man 's a human being just as i am he has just as much reason to fear me as i have"

In [212]:
generate_text(model, tokenizer, seq_len, seed_text=seed_txt, num_gen_words=25)

1/1 [==============================] - 0s 52ms/step


'the the the the the the the the the the the the the the the the the the the the the the the the the'